package com.gameobject.enums;

public enum FIELDSTATE {
    FIELD1,
    FIELD2,
    FIELD3,
    FIELD4,
    FIELD5,
    FIELD6,
    FIELD7,
    FIELD8,
    FIELDEMPTY,
    FIELDMINE,
    FIELDMINECLICKED,
    FIELDUNREVEALED,
    FIELDUNREVEALEDDEPRESSED,
    FIELDFLAGGED,
    FIELDFLAGGEDDEPRESSED,
    FIELDFlAGGEDWRONG
}
